# Numpy
* [Range in numpy](#Range-in-numpy)
* [Ones, zeros and full](#Ones,-zeros-and-full)
* [Identity matrix](#Identity-matrix)
* [Random](#Random)
* [Reshape and Ravel](#Reshape-and-Ravel)
* [Numpy Matrix Calculation and broadcasting](#Numpy-Matrix-Calculation-and-broadcasting)
* [Vectorize](#Vectorize)

In [1]:
import numpy as np

In [2]:
alist = [1,2,3]

In [3]:
np.array(alist)

array([1, 2, 3])

In [4]:
np.array(alist, dtype='float') #datatype

array([1., 2., 3.])

# Range in numpy

In [5]:
# params (start, end, step) params works like slicing 
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [6]:
# params (start, end, num_of_items)
# similar to arange 
# but third parameter is number of items to be added in array
# note: also includes end value
np.linspace(0,9,10)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Ones, zeros and full

In [7]:
# filled with ones
# params (shape, dtype)
np.ones((3,2), 'str')

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [8]:
np.zeros((1,2), 'int') # similar to ones func

array([[0, 0]])

In [9]:
# params (shape, var to add)
np.full((3,2), 3.14)

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [10]:
np.ones((3,2)) * 3.14 # same as full func but ones works for num val

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

# Identity matrix

In [11]:
# identity matrix
# params (rows, cols, start_of_diagonal, dtype,)
np.eye(3, 3, 2, int, 'F')

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

# Random

In [12]:
np.random.random(4).reshape(2,2)

array([[0.58297996, 0.7178262 ],
       [0.07953516, 0.87223058]])

In [13]:
np.random.rand(2,2)

array([[0.68034002, 0.24011736],
       [0.44584419, 0.97590095]])

In [14]:
np.random.randn(3,4)

array([[-1.61440612, -0.7972238 , -1.41912833, -0.50095532],
       [ 1.23657373, -0.13067243,  0.31966447, -0.46678215],
       [-0.15329817, -0.05895003,  0.97333108, -0.60168755]])

In [15]:
# params (range_start, range_end-1, shape)
np.random.randint(1,2, (2,2))

array([[1, 1],
       [1, 1]])

In [16]:
# seed produces same result for random func, when called before
np.random.seed(4)
np.random.randint(1, 100, size=(2,2))

array([[47, 56],
       [70,  2]])

# Reshape and Ravel

In [17]:
reshape_array = np.array([1,2,3,4,5,6])
reshape_array

array([1, 2, 3, 4, 5, 6])

In [18]:
# reshapes array to different dimension
reshape_array.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# reshapes array to 1d
reshape_array.ravel()

array([1, 2, 3, 4, 5, 6])

# Numpy Matrix Calculation and broadcasting

In [20]:
M1 = np.array([[1,10],[2,2]])
M2 = np.array([[1,2],[0,1]])

In [21]:
np.dot(M1, M2) # dot multiplication

array([[ 1, 12],
       [ 2,  6]])

In [22]:
np.linalg.inv(M2) # inverse of matrix

array([[ 1., -2.],
       [ 0.,  1.]])

In [23]:
np.transpose(M1) # transpose of matrix
M1.T # same as the above

array([[ 1,  2],
       [10,  2]])

In [24]:
np.multiply(M1,M2) # multiplying matrix(not dot product)

array([[ 1, 20],
       [ 0,  2]])

In [25]:
M1 = np.array([[1,10,3],[2,2,3]])
M2 = np.array([1,2,4])
print(M1.reshape(2,3))
print(M2.reshape(3,1))

[[ 1 10  3]
 [ 2  2  3]]
[[1]
 [2]
 [4]]


In [26]:
M1 + M2

array([[ 2, 12,  7],
       [ 3,  4,  7]])

# Vectorize

In [27]:
import time

start_time = time.time()
def myfunc(a, b):
    if a == b:
        return a + b
    
vfunc = np.vectorize(myfunc)
vfunc(np.arange(10000), np.arange(10000))
print(time.time() - start_time, "s")

0.0069386959075927734 s
